version: '3.8'

services:
  # PostgreSQL数据库
  postgres:
    image: postgres:15-alpine
    container_name: oms-postgres
    environment:
      POSTGRES_DB: oms_db
      POSTGRES_USER: oms_user
      POSTGRES_PASSWORD: oms_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - oms-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: oms-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - oms-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  oms-network:
    driver: bridge 