#!/bin/bash

echo "🔍 UI阻塞行为分析测试"
echo "============================"

# 设置JWT Token
JWT_TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsIm5hbWUiOiLmuLjlrqLnlKjmiLciLCJpYXQiOjE3NDk0MzkzODcsImV4cCI6MTc0OTUyNTc4N30.X2jv6jAtzOye2rHYEUNVY6obf8SIm9HrlQzIjWowO_A"

echo "📊 正在发送UI阻塞行为分析请求..."

curl -X POST 'http://localhost:3000/api/agent-orchestrator/analyze/quick' \
  -H 'Content-Type: application/json' \
  -H "Authorization: Bearer ${JWT_TOKEN}" \
  -d '{
    "userFeedback": "用户反馈登录页面点击登录按钮后没有反应，一直在重复点击，但是后台显示有很多请求记录，怀疑是UI响应问题",
    "logData": [
      {"id": "log-001", "timestamp": "2025-01-10T14:30:01.123Z", "level": "INFO", "source": "frontend", "service": "auth-service", "message": "用户点击登录按钮", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/login", "responseTime": 150, "userAgent": "Chrome/120.0.0.0", "action": "login_attempt"}},
      {"id": "log-002", "timestamp": "2025-01-10T14:30:01.289Z", "level": "INFO", "source": "backend", "service": "auth-service", "message": "登录请求处理成功", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/login", "responseTime": 150, "http_status": 200, "retCode": 0}},
      {"id": "log-003", "timestamp": "2025-01-10T14:30:03.456Z", "level": "INFO", "source": "frontend", "service": "auth-service", "message": "用户点击登录按钮", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/login", "responseTime": 145, "userAgent": "Chrome/120.0.0.0", "action": "login_attempt"}},
      {"id": "log-004", "timestamp": "2025-01-10T14:30:03.612Z", "level": "INFO", "source": "backend", "service": "auth-service", "message": "登录请求处理成功", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/login", "responseTime": 145, "http_status": 200, "retCode": 0}},
      {"id": "log-005", "timestamp": "2025-01-10T14:30:05.789Z", "level": "INFO", "source": "frontend", "service": "user-service", "message": "获取用户信息", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/user/profile", "responseTime": 120, "userAgent": "Chrome/120.0.0.0", "action": "get_profile"}},
      {"id": "log-006", "timestamp": "2025-01-10T14:30:05.923Z", "level": "INFO", "source": "backend", "service": "user-service", "message": "用户信息查询成功", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/user/profile", "responseTime": 120, "http_status": 200, "retCode": 0}},
      {"id": "log-007", "timestamp": "2025-01-10T14:30:07.234Z", "level": "INFO", "source": "frontend", "service": "auth-service", "message": "用户点击登录按钮", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/login", "responseTime": 155, "userAgent": "Chrome/120.0.0.0", "action": "login_attempt"}},
      {"id": "log-008", "timestamp": "2025-01-10T14:30:07.398Z", "level": "INFO", "source": "backend", "service": "auth-service", "message": "登录请求处理成功", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/login", "responseTime": 155, "http_status": 200, "retCode": 0}},
      {"id": "log-009", "timestamp": "2025-01-10T14:30:09.567Z", "level": "INFO", "source": "frontend", "service": "token-service", "message": "刷新访问令牌", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/refresh", "responseTime": 98, "userAgent": "Chrome/120.0.0.0", "action": "refresh_token"}},
      {"id": "log-010", "timestamp": "2025-01-10T14:30:09.678Z", "level": "INFO", "source": "backend", "service": "token-service", "message": "令牌刷新成功", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/refresh", "responseTime": 98, "http_status": 200, "retCode": 0}},
      {"id": "log-011", "timestamp": "2025-01-10T14:30:11.890Z", "level": "INFO", "source": "frontend", "service": "auth-service", "message": "用户点击登录按钮", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/login", "responseTime": 142, "userAgent": "Chrome/120.0.0.0", "action": "login_attempt"}},
      {"id": "log-012", "timestamp": "2025-01-10T14:30:12.045Z", "level": "INFO", "source": "backend", "service": "auth-service", "message": "登录请求处理成功", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/login", "responseTime": 142, "http_status": 200, "retCode": 0}},
      {"id": "log-013", "timestamp": "2025-01-10T14:30:13.234Z", "level": "INFO", "source": "frontend", "service": "user-service", "message": "获取用户信息", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/user/profile", "responseTime": 118, "userAgent": "Chrome/120.0.0.0", "action": "get_profile"}},
      {"id": "log-014", "timestamp": "2025-01-10T14:30:13.365Z", "level": "INFO", "source": "backend", "service": "user-service", "message": "用户信息查询成功", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/user/profile", "responseTime": 118, "http_status": 200, "retCode": 0}},
      {"id": "log-015", "timestamp": "2025-01-10T14:30:15.567Z", "level": "INFO", "source": "frontend", "service": "auth-service", "message": "用户点击登录按钮", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/login", "responseTime": 148, "userAgent": "Chrome/120.0.0.0", "action": "login_attempt"}},
      {"id": "log-016", "timestamp": "2025-01-10T14:30:15.728Z", "level": "INFO", "source": "backend", "service": "auth-service", "message": "登录请求处理成功", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/login", "responseTime": 148, "http_status": 200, "retCode": 0}},
      {"id": "log-017", "timestamp": "2025-01-10T14:30:17.890Z", "level": "INFO", "source": "frontend", "service": "token-service", "message": "刷新访问令牌", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/refresh", "responseTime": 105, "userAgent": "Chrome/120.0.0.0", "action": "refresh_token"}},
      {"id": "log-018", "timestamp": "2025-01-10T14:30:18.008Z", "level": "INFO", "source": "backend", "service": "token-service", "message": "令牌刷新成功", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/refresh", "responseTime": 105, "http_status": 200, "retCode": 0}},
      {"id": "log-019", "timestamp": "2025-01-10T14:30:19.234Z", "level": "INFO", "source": "frontend", "service": "auth-service", "message": "用户点击登录按钮", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/login", "responseTime": 139, "userAgent": "Chrome/120.0.0.0", "action": "login_attempt"}},
      {"id": "log-020", "timestamp": "2025-01-10T14:30:19.385Z", "level": "INFO", "source": "backend", "service": "auth-service", "message": "登录请求处理成功", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/login", "responseTime": 139, "http_status": 200, "retCode": 0}},
      {"id": "log-021", "timestamp": "2025-01-10T14:30:21.567Z", "level": "INFO", "source": "frontend", "service": "user-service", "message": "获取用户信息", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/user/profile", "responseTime": 125, "userAgent": "Chrome/120.0.0.0", "action": "get_profile"}},
      {"id": "log-022", "timestamp": "2025-01-10T14:30:21.705Z", "level": "INFO", "source": "backend", "service": "user-service", "message": "用户信息查询成功", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/user/profile", "responseTime": 125, "http_status": 200, "retCode": 0}},
      {"id": "log-023", "timestamp": "2025-01-10T14:30:23.890Z", "level": "INFO", "source": "frontend", "service": "auth-service", "message": "用户点击登录按钮", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/login", "responseTime": 146, "userAgent": "Chrome/120.0.0.0", "action": "login_attempt"}},
      {"id": "log-024", "timestamp": "2025-01-10T14:30:24.048Z", "level": "INFO", "source": "backend", "service": "auth-service", "message": "登录请求处理成功", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/login", "responseTime": 146, "http_status": 200, "retCode": 0}},
      {"id": "log-025", "timestamp": "2025-01-10T14:30:25.234Z", "level": "INFO", "source": "frontend", "service": "token-service", "message": "刷新访问令牌", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/refresh", "responseTime": 92, "userAgent": "Chrome/120.0.0.0", "action": "refresh_token"}},
      {"id": "log-026", "timestamp": "2025-01-10T14:30:25.338Z", "level": "INFO", "source": "backend", "service": "token-service", "message": "令牌刷新成功", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/refresh", "responseTime": 92, "http_status": 200, "retCode": 0}},
      {"id": "log-027", "timestamp": "2025-01-10T14:30:27.567Z", "level": "INFO", "source": "frontend", "service": "auth-service", "message": "用户点击登录按钮", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/login", "responseTime": 143, "userAgent": "Chrome/120.0.0.0", "action": "login_attempt"}},
      {"id": "log-028", "timestamp": "2025-01-10T14:30:27.722Z", "level": "INFO", "source": "backend", "service": "auth-service", "message": "登录请求处理成功", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/login", "responseTime": 143, "http_status": 200, "retCode": 0}},
      {"id": "log-029", "timestamp": "2025-01-10T14:30:29.890Z", "level": "INFO", "source": "frontend", "service": "user-service", "message": "获取用户信息", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/user/profile", "responseTime": 115, "userAgent": "Chrome/120.0.0.0", "action": "get_profile"}},
      {"id": "log-030", "timestamp": "2025-01-10T14:30:30.018Z", "level": "INFO", "source": "backend", "service": "user-service", "message": "用户信息查询成功", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/user/profile", "responseTime": 115, "http_status": 200, "retCode": 0}},
      {"id": "log-031", "timestamp": "2025-01-10T14:30:31.234Z", "level": "INFO", "source": "frontend", "service": "auth-service", "message": "用户点击登录按钮", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/login", "responseTime": 141, "userAgent": "Chrome/120.0.0.0", "action": "login_attempt"}},
      {"id": "log-032", "timestamp": "2025-01-10T14:30:31.387Z", "level": "INFO", "source": "backend", "service": "auth-service", "message": "登录请求处理成功", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/login", "responseTime": 141, "http_status": 200, "retCode": 0}},
      {"id": "log-033", "timestamp": "2025-01-10T14:30:33.567Z", "level": "INFO", "source": "frontend", "service": "token-service", "message": "刷新访问令牌", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/refresh", "responseTime": 89, "userAgent": "Chrome/120.0.0.0", "action": "refresh_token"}},
      {"id": "log-034", "timestamp": "2025-01-10T14:30:33.668Z", "level": "INFO", "source": "backend", "service": "token-service", "message": "令牌刷新成功", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/refresh", "responseTime": 89, "http_status": 200, "retCode": 0}},
      {"id": "log-035", "timestamp": "2025-01-10T14:30:35.890Z", "level": "INFO", "source": "frontend", "service": "auth-service", "message": "用户点击登录按钮", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/login", "responseTime": 147, "userAgent": "Chrome/120.0.0.0", "action": "login_attempt"}},
      {"id": "log-036", "timestamp": "2025-01-10T14:30:36.049Z", "level": "INFO", "source": "backend", "service": "auth-service", "message": "登录请求处理成功", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/login", "responseTime": 147, "http_status": 200, "retCode": 0}},
      {"id": "log-037", "timestamp": "2025-01-10T14:30:37.234Z", "level": "INFO", "source": "frontend", "service": "user-service", "message": "获取用户信息", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/user/profile", "responseTime": 122, "userAgent": "Chrome/120.0.0.0", "action": "get_profile"}},
      {"id": "log-038", "timestamp": "2025-01-10T14:30:37.368Z", "level": "INFO", "source": "backend", "service": "user-service", "message": "用户信息查询成功", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/user/profile", "responseTime": 122, "http_status": 200, "retCode": 0}},
      {"id": "log-039", "timestamp": "2025-01-10T14:30:39.567Z", "level": "INFO", "source": "frontend", "service": "auth-service", "message": "用户点击登录按钮", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/login", "responseTime": 144, "userAgent": "Chrome/120.0.0.0", "action": "login_attempt"}},
      {"id": "log-040", "timestamp": "2025-01-10T14:30:39.723Z", "level": "INFO", "source": "backend", "service": "auth-service", "message": "登录请求处理成功", "metadata": {"userId": "user-888", "sessionId": "session-ui-block", "apiEndpoint": "/api/auth/login", "responseTime": 144, "http_status": 200, "retCode": 0}}
    ],
    "options": {
      "pipeline": "PARALLEL",
      "priority": "HIGH"
    }
  }' | jq '.'

echo ""
echo "✅ UI阻塞行为分析完成！" 