version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_management
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image: docker-0.unsee.tech/adminer
    ports:
      - 8080:8080
  redis:
    image: docker-0.unsee.tech/redis:6.2
    restart: always
    command: ["redis-server", "--requirepass", "123456"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data: