services:
  db:
    image: docker-0.unsee.tech/pgvector/pgvector:pg16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_management
      POSTGRES_MULTIPLE_DATABASES: n8n
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - n8n-network
  adminer:
    image: docker-0.unsee.tech/adminer
    ports:
      - 8081:8080
    networks:
      - n8n-network
  redis:
    image: docker-0.unsee.tech/redis:6.2
    restart: always
    command: ["redis-server", "--requirepass", "123456"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - n8n-network
  
  n8n:
    image: docker-0.unsee.tech/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    networks:
      - n8n-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 8.8.8.8
      - 114.114.114.114
      - 1.1.1.1
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Asia/Shanghai
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_HOST=smtp.example.com
      - N8N_SMTP_PORT=587
      - N8N_SMTP_USER=user@example.com
      - N8N_SMTP_PASS=password
      - N8N_SMTP_SENDER=sender@example.com
      - N8N_SMTP_SSL=true
      - LANGS='zh-CN,en-US'
      - N8N_USER_MANAGEMENT_DISABLED=false
      - N8N_USER_EMAIL=admin@example.com
      - N8N_USER_PASSWORD=password
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=postgres
    volumes:
      - n8n_data:/home/node/.n8n
      - ./server/n8n-workflows-main/workflows:/workflows
    depends_on:
      - db
      - redis

networks:
  n8n-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16

volumes:
  db_data:
  redis_data:
  n8n_data: